# Generated by Django 4.1.1 on 2024-07-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employeeNumber", models.IntegerField()),
                ("lastName", models.CharField(max_length=20)),
                ("firstName", models.CharField(max_length=20)),
                ("extension", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("officeCode", models.IntegerField()),
                ("jobTitle", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=20)),
                ("phone", models.BigIntegerField()),
                ("reportsTo", models.IntegerField()),
                ("reportToLastName", models.CharField(max_length=30)),
                ("reportToFirstName", models.CharField(max_length=30)),
            ],
        ),
    ]
