# Generated by Django 4.1.8 on 2023-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prduct_name", models.CharField(max_length=25)),
                ("ram", models.IntegerField()),
                ("rom", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
