# Generated by Django 4.1.8 on 2023-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=25)),
                ("start", models.CharField(max_length=25)),
                ("end", models.CharField(max_length=25)),
            ],
        ),
    ]
