# Generated by Django 4.1.8 on 2023-08-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarDetailsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=25)),
                ("hp", models.IntegerField()),
                ("color", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
