# Generated by Django 4.1.8 on 2023-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JaguarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=10)),
                ("hp", models.IntegerField()),
                ("color", models.CharField(max_length=10)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
